blank_issues_enabled: true
contact_links:
  - name: Questions & ideas
    url: https://github.com/dhosruiasn/ui-tweaker/issues/new/choose
    about: For open-ended questions, ideas, show-and-tell, and general Q&A.
